import { Dictionary } from "./dictionary";

export const DE: Dictionary = {
    'cancel': 'Abbrechen',
    'game.joker': 'Joker',
    'game.joker.action': 'Aktion',
    'game.joker.action.cleanup': 'Aufräumen',
    'game.joker.action.delete': 'Löschen',
    'game.joker.action.pauseInject': 'Einwurf Pause',
    'game.joker.action.injectNew': 'Neu einwerfen',
    'game.joker.action.undo': 'Rückgängig',
    'game.joker.costs': 'Kosten',
    'game.mode': 'Modus',
    'game.over': 'Spiel zuende',
    'game.score': 'Punkte',
    'hiscore.max': 'Max',
    'menu': 'Menu',
    'menu.back': 'Zurück',
    'menu.hiscore': 'Rekorde',
    'menu.level1': 'Einfach',
    'menu.level2': 'Schwer',
    'menu.new': 'Neues Spiel',
    'menu.resume': 'Spiel fortsetzen',
    'menu.settings': 'Einstellungen',
    'menu.start': 'Start',
    'theme.bright': 'Hell',
    'theme.dark': 'Dunkel',
    'title': 'Numbers',
    'version': 'Version'
};